### PR TITLE
fix(death): unstack items for kept or lost classification

### LINKED ISSUE #252: Improve Death loot value for noted/stackable items
Loot value for inside looting bag and noted items does not count to the worth. Is there a way to incorporate this?

### PR DESCRIPTION
**Pull request by iProdigy**
Closes #252

### CODE REVIEW

**Comment by iProdigy** [comment]
✅ In-game debug test:

### Shell
```java
var em = inject(net.runelite.client.eventbus.EventBus.class);
em.post(new ActorDeath(client.getLocalPlayer()));
```

### Notification
image

### JSON
```json
{
  "type": "DEATH",
  "playerName": "dankgg",
  "accountType": "NORMAL",
  "extra": {
    "valueLost": 114079,
    "isPvp": false,
    "keptItems": [
      {
        "id": 1044,
        "quantity": 1,
        "priceEach": 10646,
        "name": "Green partyhat"
      },
      {
        "id": 533,
        "quantity": 1,
        "priceEach": 229,
        "name": "Big bones"
      },
      {
        "id": 533,
        "quantity": 1,
        "priceEach": 229,
        "name": "Big bones"
      }
    ],
    "lostItems": [
      {
        "id": 533,
        "quantity": 498,
        "priceEach": 229,
        "name": "Big bones"
      },
      {
        "id": 1061,
        "quantity": 1,
        "priceEach": 37,
        "name": "Leather boots"
      }
    ]
  },
  "embeds": [
    {
      "title": "Player Death",
      "description": "dankgg has died, losing 114079 gp",
      "author": {
        "name": "dankgg",
        "url": "https://secure.runescape.com/m=hiscore_oldschool/hiscorepersonal?user1=dankgg"
      },
      "color": 15990936,
      "image": {
        "url": "attachment://deathImage.png"
      },
      "thumbnail": {
        "url": "https://oldschool.runescape.wiki/images/Items_kept_on_death.png"
      },
      "fields": [],
      "footer": {
        "text": "Powered by Dink",
        "icon_url": "https://github.com/pajlads/DinkPlugin/raw/master/icon.png"
      },
      "timestamp": "2023-06-14T16:53:17.881912800Z"
    }
  ]
}
```

**Review by Felanbird — APPROVED** [review]
```
{
   "type":"DEATH",
   "playerName":"felanbird1",
   "accountType":"NORMAL",
   "extra":{
      "valueLost":1080,
      "isPvp":true,
      "pker":"pajdank",
      "killerName":"pajdank",
      "keptItems":[
         {
            "id":5698,
            "quantity":1,
            "priceEach":22371,
            "name":"Dragon dagger(p++)"
         },
         {
            "id":3144,
            "quantity":1,
            "priceEach":501,
            "name":"Cooked karambwan"
         },
         {
            "id":8013,
            "quantity":1,
            "priceEach":427,
            "name":"Teleport to house"
         }
      ],
      "lostItems":[
         {
            "id":1892,
            "quantity":2,
            "priceEach":113,
            "name":"Cake"
         },
         {
            "id":892,
            "quantity":5,
            "priceEach":104,
            "name":"Rune arrow"
         },
         {
            "id":526,
            "quantity":1,
            "priceEach":54,
            "name":"Bones"
         },
         {
            "id":1988,
            "quantity":5,
            "priceEach":15,
            "name":"Grapes"
         },
         {
            "id":1981,
            "quantity":19,
            "priceEach":10,
            "name":"Empty cup"
         },
         {
            "id":1994,
            "quantity":5,
            "priceEach":3,
            "name":"Jug of wine"
         }
      ]
   },
   "embeds":[
      {
         "title":"Player Death",
         "description":"felanbird1 has just been PKed by pajdank for 1080 gp...",
         "author":{
            "name":"felanbird1",
            "url":"https://secure.runescape.com/m\u003dhiscore_oldschool/hiscorepersonal?user1\u003dfelanbird1"
         },
         "color":15990936,
         "image":{
            "url":"attachment://deathImage.png"
         },
         "thumbnail":{
            "url":"https://oldschool.runescape.wiki/images/Items_kept_on_death.png"
         },
         "fields":[
            
         ],
         "footer":{
            "text":"Powered by Dink",
            "icon_url":"https://github.com/pajlads/DinkPlugin/raw/master/icon.png"
         },
         "timestamp":"2023-06-14T17:22:10.959100900Z"
      }
   ]
}
```

**Comment by Felanbird** [comment]
normal death
```
{
   "type":"DEATH",
   "playerName":"felanbird1",
   "accountType":"NORMAL",
   "extra":{
      "valueLost":1348,
      "isPvp":false,
      "killerName":"Adamant dragon",
      "killerNpcId":8030,
      "keptItems":[
         {
            "id":5698,
            "quantity":1,
            "priceEach":22347,
            "name":"Dragon dagger(p++)"
         },
         {
            "id":8013,
            "quantity":1,
            "priceEach":432,
            "name":"Teleport to house"
         },
         {
            "id":8013,
            "quantity":1,
            "priceEach":432,
            "name":"Teleport to house"
         }
      ],
      "lostItems":[
         {
            "id":8013,
            "quantity":2,
            "priceEach":432,
            "name":"Teleport to house"
         },
         {
            "id":1518,
            "quantity":25,
            "priceEach":13,
            "name":"Maple logs"
         },
         {
            "id":1733,
            "quantity":1,
            "priceEach":4,
            "name":"Needle"
         },
         {
            "id":1994,
            "quantity":10,
            "priceEach":3,
            "name":"Jug of wine"
         },
         {
            "id":7937,
            "quantity":25,
            "priceEach":2,
            "name":"Pure essence"
         },
         {
            "id":1780,
            "quantity":25,
            "priceEach":2,
            "name":"Flax"
         },
         {
            "id":52,
            "quantity":25,
            "priceEach":1,
            "name":"Arrow shaft"
         }
      ]
   },
```

**Review by pajlada — APPROVED** [review]
Code looks good to me :+1:

**Pull request merged**
