### PR TITLE
feat: add raid party members to loot metadata

### LINKED ISSUE #477: Send group data when getting drop from group content
### Checklist

- [x] I've searched the [issues and pull requests](https://github.com/pajlads/Dinkplugin/issues?q=) for similar looking suggestions.
- [X] I've checked the `Unreleased` section of the [changelog](https://github.com/pajlads/DinkPlugin/blob/master/CHANGELOG.md) for newly added features that sound like my suggestion.

### Describe your Suggestion

Would be very cool to list the members inside a raid or group kc as a field like:

```
{
  "content": "%USERNAME% has looted: \n\n%LOOT%\nFrom: %SOURCE%",
  "extra": {
    "items": [
      {
        "id": 1234,
        "quantity": 1,
        "priceEach": 42069727,
        "name": "Some expensive raid item"
      }
    ],
    "source": "Very difficult raid",
    "category": "NPC",
    "killCount": 60,
    "rarestProbability": 0.001,
    "group": [
        "player1",
        "player2",
        "player3"
    ]
  },
  "type": "LOOT"
}
```

### Reasoning

Would be very helpful as my web server is currently parsing dink data to handle automating our clan events, and group data can help automate split gp tracking, group-based event tracking, clan participation metrics, etc.

Have not really thought through any edge cases or implications of trying to find this data but thought I'd ask if it was possible :P

### PR DESCRIPTION
**Pull request by iProdigy**
Closes #477

### CODE REVIEW

**Review by pajlada — APPROVED** [review]
Code looks great :+1: Haven't tested in-game

**Review by Felanbird — APPROVED** [review]
i don't have a raiding gang laying around either so we'll just assume it works

**Comment by iProdigy** [comment]
@zneix would you be willing to test this branch next time u do cox & toa? (essentially just trigger the loot notification & lepp can grab the json to verify)

shadow jar: https://github.com/pajlads/DinkPlugin/actions/runs/9146741541/artifacts/1516909819

**Comment by zneix** [comment]
Sure thing, I'll give it a show in the coming days.

**Comment by zneix** [comment]
From a casual solo ToA run I've managed to produce this payload 
```json
{"type":"LOOT","playerName":"zneix","accountType":"NORMAL","dinkAccountHash":"e3791a53061d0458cd4e3a080277e36d7b871d12c4642be8377b77c3","clanName":"Tench","seasonalWorld":false,"extra":{"items":[{"id":5935,"quantity":29,"priceEach":241,"name":"Coconut milk"},{"id":1391,"quantity":29,"priceEach":7971,"name":"Battlestaff"},{"id":560,"quantity":1660,"priceEach":113,"name":"Death rune"}],"source":"Tombs of Amascut","category":"EVENT","killCount":164,"party":["zneix"]},"discordUser":{"id":"288028423031357441","name":"zneix","avatarHash":"89a62e8d973219b4abd89769057a0f03"},"content":"zneix has looted: \n\n29 x Battlestaff (231K)\n1660 x Death rune (187K)\nFrom: Tombs of Amascut","embeds":[]}
```

**Comment by zneix** [comment]
Another test, in a duo ToA this time https://paste.ivr.fi/raw/epasurydus (copied below)
```json
{"type":"LOOT","playerName":"zneix","accountType":"NORMAL","dinkAccountHash":"e3791a53061d0458cd4e3a080277e36d7b871d12c4642be8377b77c3","clanName":"Tench","seasonalWorld":false,"extra":{"items":[{"id":6016,"quantity":38,"priceEach":1943,"name":"Cactus spine"},{"id":26390,"quantity":2,"priceEach":59362,"name":"Blood essence"},{"id":27293,"quantity":1,"priceEach":100,"name":"Cache of runes"}],"source":"Tombs of Amascut","category":"EVENT","killCount":164,"party":["zneix","PolskaPride"]},"discordUser":{"id":"288028423031357441","name":"zneix","avatarHash":"89a62e8d973219b4abd89769057a0f03"},"content":"zneix has looted: \n\n38 x Cactus spine (73.8K)\n2 x Blood essence (118K)\n1 x Cache of runes (100)\nFrom: Tombs of Amascut","embeds":[]}
```

**Comment by zneix** [comment]
Interestingly enough the CoX seems to not function properly with the raid members https://paste.ivr.fi/raw/abysovasiz (copied below)
this was a regular mode raid with 6 people
```json
{"type":"LOOT","playerName":"zneix","accountType":"NORMAL","dinkAccountHash":"e3791a53061d0458cd4e3a080277e36d7b871d12c4642be8377b77c3","clanName":"Tench","seasonalWorld":false,"extra":{"items":[{"id":447,"quantity":774,"priceEach":103,"name":"Mithril ore"},{"id":2485,"quantity":99,"priceEach":1438,"name":"Grimy lantadyme"}],"source":"Chambers of Xeric","category":"EVENT","killCount":44,"party":[]},"discordUser":{"id":"288028423031357441","name":"zneix","avatarHash":"89a62e8d973219b4abd89769057a0f03"},"content":"zneix has looted: \n\n99 x Grimy lantadyme (142K)\nFrom: Chambers of Xeric","embeds":[]}
 ```

**Comment by iProdigy** [comment]
I just tested CoX - jagex doesn't populate the widget unless the Grouping tab is selected (but can be minimized)

with the tab selected, it looks like the code obtains the names correctly

image

**Pull request merged**
