### PR TITLE
feat: include wiki links in rich embeds

### PR DESCRIPTION
**Pull request by iProdigy**
Closes #241

Notifiers without wiki links:
* Player Kill (for another PR as it will use player lookup service rather than wiki)
* Pet (because `%PET%` is not currently a pattern since obtaining the name can be unreliable)
* Group Storage (because diff codeblock prevents item links)

### Achievement Diary
image

* https://oldschool.runescape.wiki/w/Special:Search?search=Karamja%20Diary

### BA Gambles
image

* https://oldschool.runescape.wiki/w/Special:Search?search=Dragon%20chainbody

### Clue
image

* https://oldschool.runescape.wiki/w/Special:Search?search=Clue%20scroll%20(medium)
* https://oldschool.runescape.wiki/w/Special:Search?search=Ruby

### Collection
image

* https://oldschool.runescape.wiki/w/Special:Search?search=Seercull

### Combat Task
image

* https://oldschool.runescape.wiki/w/Special:Search?search=No%20Pressure

### Death
image

* https://oldschool.runescape.wiki/w/Special:Search?search=Guard

### Level
image

* https://oldschool.runescape.wiki/w/Special:Search?search=Hitpoints
* https://oldschool.runescape.wiki/w/Special:Search?search=Combat%20level

### Loot
image

* https://oldschool.runescape.wiki/w/Special:Search?search=Ruby
* https://oldschool.runescape.wiki/w/Special:Search?search=Opal

### Kill Count
image

* https://oldschool.runescape.wiki/w/Special:Search?search=Tombs%20of%20Amascut:%20Expert%20Mode

### Quest
image

* https://oldschool.runescape.wiki/w/Special:Search?search=Dragon%20Slayer%20I

### Slayer
image

* https://oldschool.runescape.wiki/w/Special:Search?search=Chaos%20Elemental

### Speedrun
image

* https://oldschool.runescape.wiki/w/Special:Search?search=Cook%27s%20Assistant

### CODE REVIEW

**Review by pajlada — APPROVED** [review]
I've looked through the full PR and code-wise this looks good to me - the plan for future PRs also seems good :+1: 

Is it possible to make the Template class builder require the template as part of the constructor rather than as a separate function call?

so I'd like:
```java
Template.TemplateBuilder template = Template.builder("Cool %ITEM%")
    .replacement(...)
    .build();
```

rather than
```java
Template.TemplateBuilder template = Template.builder()
    .template("Cool %ITEM%")
    .replacement(...)
    .build();
```

If this is not possible/not common in Java that's fine, it's just how I would've built if I did it manually

**Comment by iProdigy** [comment]
> Is it possible to make the Template class builder require the template as part of the constructor rather than as a separate function call?

Unfortunately lombok's `@Builder` doesn't support that (needs no args constructor) and isn't common in Java... we *could* delombok the class & implement this ourselves, but I don't think it's worth the explosion of boilerplate

**Comment by pajlada** [comment]
Yeah, in the end it's mostly a convenience factor which opens up neater convenience factors in the future (like linking to player lookup services)

**Comment by iProdigy** [comment]
> Though from a brief skim of the code, it might not be as easy as I'd like

Yeah clue & diary would be too complicated to implement that way (since it's not part of the replacement)

Slayer, on the other hand, could be modified... but involves some refactoring, so I'd leave this for another PR

**Review by Felanbird — APPROVED** [review]
seems fine then, we'll see what happens with this 👍

**Pull request merged**
