### PR TITLE
Update hub icon with a festive version.

### PR DESCRIPTION
**Pull request by notheowner**
Add discord logo to Dink emote.
1st version: 
dinkFinalMaybe

Bonus Batman version
icon

Santa version
dinkSanta

### CODE REVIEW

**Comment by Mm2PL** [comment]
I don't think we have the rights to use the discord logo

**Review by pajlada — APPROVED** [review]
I'm fine to try this out :+1:

**Review by Mm2PL — CHANGES_REQUESTED** [review]
The [Discord brand usage guidelines](https://discord.com/branding) are very unclear on weather we can use the logo unmodified as a part of our icon or even *at all*. However they do clearly state that the logo is not to be modified. I would rather be careful and not do this.

**Comment by notheowner** [comment]
Discord icon on pause for now.
Santa hat version of pajaDink.
dinkSanta

**Review by Felanbird — APPROVED** [review]
chrimbus

**Review by iProdigy — APPROVED** [review]

**Review by Mm2PL — APPROVED** [review]

**Pull request merged**
