### PR TITLE
fix: ensure boss name is in slayer task message

### LINKED ISSUE #87: Mention boss name in Boss Slayer notifications
Currently Slayer notifications for bosses don't mention boss name since it's not included in the task complete message.
image
Looking at the game chat log, game sends a message regarding the name of the Boss and maybe location if on Konar task(unconfirmed), right before the task completion text.
image
Maybe support could be added for that.

### PR DESCRIPTION
**Pull request by iProdigy**
Fixes #87

### CODE REVIEW

**Review by Felanbird — CHANGES_REQUESTED** [review]
image
Luckily I got a Barrows task, but what other patterns are there 👺

**Review by pajlada — APPROVED** [review]
Tested on a Chaos Elemental task, works as expected

Chat box: 
image

Final notification:
image

The relevant request fields:
```
extra: {
      "slayerTask": "11 Chaos Elemental",
      "slayerCompleted": "242",
      "slayerPoints": "15"
    }
    playerName: "pajdank"
    message: "pajdank has completed a slayer task: 11 Chaos Elemental, getting 15 points and making that 242 tasks completed"
```

**Comment by pajlada** [comment]
Sarachnis, using stable version so I don't expect it to work just posting here to keep the message somewhere :smile: 
image

**Comment by pajlada** [comment]
King Black Dragon, just adding it here for reference
image

**Pull request merged**
