### PR TITLE
feat(metadata): include hashed account unique identifier

### LINKED ISSUE #333: Feature request: Send account hash (or a derivative of it) along with display name
I was recently made aware of https://static.runelite.net/api/runelite-api/com/jagex/oldscape/pub/OAuthApi.html#getAccountHash()

For my application it would be a great help if events were to send along this hash or an unique identifier derived from it (e.g. sha256) to keep track of name changes.

### PR DESCRIPTION
**Pull request by iProdigy**
Closes #333

Uses SHA-224 as a sufficiently fast (my laptop achieves a throughput of over 2 million hashes per second, according to JMH) hash function (that doesn't require adding a new dependency) with resistance to collision attacks, preimage attacks, and length extension attacks, so that the underlying account identifier is not revealed (just in case other third party applications use this identifier as auth). If SHA-224 is not available (i.e., user has a very exotic JVM), `dinkAccountHash` is not specified.

### CODE REVIEW

**Review by pajlada — COMMENTED** [review]
We could use https://static.runelite.net/api/runelite-api/net/runelite/api/events/AccountHashChanged.html and just apply our own hash when it changes

Also random question: Is there a case where a user uses a non-discord dink URL but doesn't want their account hash shared? I think no but maybe someone else thinks differently

could the sha224 function just be a dinkHash function, comment stating that it's sha224 with a salt, so the usages of it doesn't have to do the offsets themselves?

**Comment by iProdigy** [comment]
> We could use https://static.runelite.net/api/runelite-api/net/runelite/api/events/AccountHashChanged.html and just apply our own hash when it changes

Yeah we can cache the dink hash if the extra memory is worth the compute savings

&nbsp;

> Also random question: Is there a case where a user uses a non-discord dink URL but doesn't want their account hash shared? I think no but maybe someone else thinks differently

Only possibility is that a user wants to reset their profile on a third-party service that tracks `dinkAccountHash` (but doesn't natively offer a reset function), and continue using that service with a fresh slate... so much so that the user is willing to change their in-game name to accomplish this. Seems far fetched?

&nbsp;

> could the sha224 function just be a dinkHash function, comment stating that it's sha224 with a salt, so the usages of it doesn't have to do the offsets themselves?

Done & changed "offset"/constant-salt with padding

**Comment by pajlada** [comment]
for using the accounthashchanged, I see it as more of a benefit of "readability", where we use the built-in event to make sure sure the value is always up-to-date based on what runelite tells us\

**Comment by iProdigy** [comment]
Currently we do `Client#getAccountHash` on every notification, which will always retrieve the most up-to-date value.

We can integrate `accounthashchanged`, but can't completely remove `Client#getAccountHash` since people could disable dink, change account, and enable dink again (so we'd miss the `accounthashchanged` event)

**Comment by pajlada** [comment]
riiiiiiight, that's fair

I was thinking we might be caching the value in the body or something - I didn't read the full context of the `enrichBody` call

should be good as is then, unless anyone can come up with a non-crazy reason people would want to hide their hashed account hash

**Review by pajlada — APPROVED** [review]
haven't tested but looks good to me, should be easy enough for servers to implement

**Comment by iProdigy** [comment]
Sample payload

```json
{
  "type": "LOGIN",
  "playerName": "FerrousDink",
  "accountType": "HARDCORE_GROUP_IRONMAN",
  "dinkAccountHash": "ee819b5a889088df2222ec18e04aa211ecd342c4700dfd8b2703295c",
  "groupIronClanName": "Dink QA",
  "extra": {
    "world": 430,
    "combatAchievementPoints": {
      "completed": 0,
      "total": 1884
    },
    "achievementDiary": {
      "completed": 0,
      "total": 48
    },
    "achievementDiaryTasks": {
      "completed": 0,
      "total": 492
    },
    "barbarianAssault": {
      "highGambleCount": 0
    },
    "skills": {
      "totalExperience": 1867,
      "totalLevel": 36,
      "levels": {
        "Hunter": 1,
        "Thieving": 1,
        "Runecraft": 1,
        "Construction": 1,
        "Cooking": 2,
        "Magic": 1,
        "Fletching": 1,
        "Herblore": 1,
        "Firemaking": 1,
        "Attack": 1,
        "Fishing": 1,
        "Crafting": 1,
        "Hitpoints": 10,
        "Ranged": 1,
        "Mining": 1,
        "Smithing": 1,
        "Agility": 1,
        "Woodcutting": 1,
        "Slayer": 1,
        "Defence": 1,
        "Strength": 3,
        "Prayer": 2,
        "Farming": 1
      }
    },
    "questCount": {
      "completed": 0,
      "total": 158
    },
    "questPoints": {
      "completed": 0,
      "total": 300
    },
    "slayer": {
      "points": 0,
      "streak": 0
    }
  }
}
```

**Review by Felanbird — APPROVED** [review]
works well enough for me :+1:

**Pull request merged**
