### PR TITLE
feat: indicate duplicate pet drops

### LINKED ISSUE #292: Allow different notification message for dupe pets
I believe it should be easy enough to differentiate given the game message is different when receiving a duplicate pet?

### PR DESCRIPTION
**Pull request by iProdigy**
Closes #292

image

### CODE REVIEW

**Review by pajlada — APPROVED** [review]
Looks like a good solution to me :+1:  I can't find any other message variations that I can add as test cases, so if it's a case we don't capture (e.g. pet already out & getting a duplicate) we can just fix it as it comes out

**Review by Felanbird — APPROVED** [review]
The edge-case will be when a user's pet is in insurance limbo (death with pet out), the message for the next pet will be normal as I believe you actually get the pet again.

But that's not really something we can deal with, the only not-really-within-your-control is low level UIMs as they don't yet have the menagerie in the PoH (or a bank) so their deaths with a pet out tend to be strategy, not mistake.

**Comment by zneix** [comment]
I only have seen this now and just want to add to Felanbird's comment regarding receiving duplicate pets in specific cases. I got a beaver once, it died so I'd have to reclaim it but before doing so I got another one. The message in chat has indeed been "she's being followed" instead of "would have been followed" however the distinction between getting first ever beaver is that I didn't get a note about pet being autoinsured along the "tutorial" message saying I can reclaim the pet from Probita later. I see that this has now been implemented and is the sealed deal, but if someone wants to maybe change the logic later, here's my suggestion to switch to detecting pet insurance messages.
I'll try to find screenshots and attach them later to give an example of the differences.

**Comment by iProdigy** [comment]
Appreciate the info, @zneix 

As you said, only way to reliably fix that edge case is to use collection log messages (will do in another PR)

**Pull request merged**
