### PR TITLE
perf: rescale screenshots on background thread

### PR DESCRIPTION
**Pull request by iProdigy**
Not the solution for #377, but still useful

### CODE REVIEW

**Comment by iProdigy** [comment]
only downside: if there's a bad plugin simultaneously submitting long-running jobs to this executor, unhiding chat widget could take longer (but we can refactor this approach to schedule unhide on renderer thread instead of executor thread)

**Review by pajlada — APPROVED** [review]
On big resolution I got a little bit of lag without the PR, and zero lag with the PR.
I did not test chat hiding.
Code looks good to me :+1:

**Comment by iProdigy** [comment]
i've also been running this PR & haven't had any chat-hiding issues

**Review by Felanbird — APPROVED** [review]
I see no noticeable issues with this change 👍

**Pull request merged**
