### PR TITLE
feat: use chat boss kc message for loot notification metadata

### LINKED ISSUE #323: Loot broadcasts showing kc from loot tracker, not actual kc
Currently loot broadcasts are displaying the kc previously recorded by the loot tracker, not the actual account kc. 
Image below for reference (account has 2700+ kc but broadcast says 211)
Thanks
image

### PR DESCRIPTION
**Pull request by iProdigy**
Closes #323 (follow-up from #299)

### CODE REVIEW

**Comment by Felanbird** [comment]
test #1 KBD:

The first issue makes me think of the ConfigManager problem from before, but unsure if it is.
First KC notifies with the loot tracker KC, all others afterwards use boss KC.
Banking the trip and returning the same thing happens, KC 1 uses loot tracker, all others use KC.
Doing a 1KC trip and returning, KC 1 (time wise actually 2) works as expected.

**Comment by iProdigy** [comment]
Correct, the current patch uses loot tracker kc for the first boss kill of the session & chat messages beyond that (because I'm afraid of some edge case where boss kc message happens after the loot event)

**Comment by iProdigy** [comment]
Actually I have an idea to use boss kc message if it appears before the first loot event, will implement tonight

**Review by pajlada — APPROVED** [review]
Logic seems good, haven't tested in-game

**Comment by Felanbird** [comment]
test `#2` kbd again: works as I would expect it to

**Comment by Felanbird** [comment]
test `#3` hespori: failed, but hespori might not be an applicable case for this PR, as his loot comes from harvesting his corpse, not an actual loot drop
image

**Comment by Felanbird** [comment]
test `#4` alch hydra: works

**Comment by Felanbird** [comment]
test `#5` bryophyta & obor: both worked as expected, both had no loot tracker history

test `#6` duke: worked as expected, had loot tracker history

**Review by Felanbird — APPROVED** [review]
I can't think of any non-normal bosses that this PR shouldn't work for :+1:

**Pull request merged**
