### PR TITLE
feat: Include world and regionId as metadata with every notifier message

### PR DESCRIPTION
**Pull request by BlackCoyote**
This pull request consists of changes that include a "world" and "regionId" property in the NotificationBody, so that they are included with every derived notification message. These properties are automatically populated in the DiscordMessageHandler if they hadn't been populated otherwise.

With the world property you can always know which world the notifying user is in, even after world hopping. (LoginNotifier does not act upon world hops), which allows for:
- Better understanding what kind of seasonal world the player is in. (Assuming Deadman Mode, Leagues, and Beta worlds are all seasonal)

With the regionId property you can always know where in the world the notifying user is in, which allows for:
- Better understanding certain identical chat messages in different scenarios. (For example: "Wave: X" in the Inferno, Fortis Colosseum, and the Fight caves.)
- Make educated guesses about the context of various other kinds of notifier messages. (For example, the training method used during a level/xp notifier message.)
- Build more interesting custom notifier messages across the board by including the region name.

I believe the world and regionId to be very valuable context for various notifiers, and harmless enough to include with every notifier message by default.

### CODE REVIEW

**Comment by BlackCoyote** [comment]
I'm afraid I don't understand why the notifier tests would throw an NPE. Any insight would be appreciated. Thanks!

**Comment by iProdigy** [comment]
not every notifier has the player's location defined, which causes an NPE when trying to get the region id - you can fix this by adding this line to `MockedNotifierTest#setUp`:

```java
when(localPlayer.getWorldLocation()).thenReturn(new WorldPoint(2500, 2500, 0))
```

(i just chose a random location)

**Comment by BlackCoyote** [comment]
> not every notifier has the player's location defined, which causes an NPE when trying to get the region id - you can fix this by adding this line to `MockedNotifierTest#setUp`:
> 
> ```java
> when(localPlayer.getWorldLocation()).thenReturn(new WorldPoint(2500, 2500, 0))
> ```
> 
> (i just chose a random location)

Thanks. Is the World already provided some way, or should that be added too?

**Comment by iProdigy** [comment]
Since world is an int, mockito defaults that to 0

**Comment by iProdigy** [comment]
We should have an advanced config setting to be able to opt-out of sending this data. For the pk notifier, for example, we have `pkIncludeLocation` (defaults to true).

with this new setting, the pk-specific setting could be removed. this would also require config migration code to set the new config value to false if the user set `pkIncludeLocation` to false - let us know if you'd prefer a maintainer to add this code

**Comment by BlackCoyote** [comment]
That makes sense. I'll take you up on that offer to have a maintainer implement that, if that's alright.

**Review by pajlada — APPROVED** [review]

**Review by pajlada — COMMENTED** [review]
I would maybe update the changelog entry to clarify that this is enabled by default, and only accessible to non-discord webhooks, and make it a non-Dev entry

**Comment by iProdigy** [comment]
@Felanbird is it bad UX that pk notifier location setting is moved to advanced section without any clear indication? (i.e., should we have 2 config settings for this)

**Comment by Felanbird** [comment]
> @Felanbird is it bad UX that pk notifier location setting is moved to advanced section without any clear indication? (i.e., should we have 2 config settings for this)

I would say yes, I assume PKers would perpetrate the same issues as sweats and not read the version bump chat message, even if the only bump info was `MOVED SETTING TO ADVANCED SECTION`

**Review by pajlada — APPROVED** [review]

**Comment by iProdigy** [comment]
:white_check_mark: tested in-game

```json
{
  "type": "LOOT",
  "playerName": "dankgg",
  "accountType": "NORMAL",
  "dinkAccountHash": "172d48fcbfce074e5385d67760091497dd5a761d97d19e871586ec54",
  "content": "dankgg has looted: \n\n1 x Big bones (306)\n3 x Law rune (357)\n\nFrom: Moss giant",
  "seasonalWorld": false,
  "world": 393,
  "regionId": 12698,
  "extra": {
    "items": [
      {
        "id": 532,
        "quantity": 1,
        "priceEach": 306,
        "name": "Big bones"
      },
      {
        "rarity": 0.03125,
        "id": 563,
        "quantity": 3,
        "priceEach": 119,
        "name": "Law rune"
      }
    ],
    "source": "Moss giant",
    "category": "NPC",
    "killCount": 2344,
    "rarestProbability": 0.03125
  }
}
```

**Pull request merged**
