### PR TITLE
 feat: add party to kc metadata

### PR DESCRIPTION
**Pull request by iProdigy**
Completes the party aspect of #585

### CODE REVIEW

**Review by pajlada — APPROVED** [review]
Code looks good, would like to see what's changed in the discord notifications. Haven't tested

**Comment by iProdigy** [comment]
sample discord notif 
image

**Comment by pajlada** [comment]
Does this change modify the loot notifier if you're in a raid?

**Comment by iProdigy** [comment]
shouldn't be any change to the loot notifier from this PR (that embed already has the same `Party Size` field)

**Review by Felanbird — APPROVED** [review]
works for 1player party

**Pull request merged**
