### PR TITLE
feat: add maxed skills field on 99 level up

### PR DESCRIPTION
**Pull request by iProdigy**
For discussion following https://github.com/pajlads/DinkPlugin/pull/110#discussion_r1064125140

### CODE REVIEW

**Comment by pajlada** [comment]
The purpose of this is: When the user hits 99 in a skill, this will show all the other skills the user is already 99 in

Right?

**Comment by iProdigy** [comment]
Correct, upon hitting 99 exactly in any skill, a field is added indicating how many total maxed skills the player has

**Comment by pajlada** [comment]
I think the field should be updated to be a bit clear that that's what happened

"New 99 skill(s)!: Firemaking"
"Previous 5 99 skill(s): Combat, Attack, Agility, Mining, Runecrafting"

Not sure if it should be two separate fields, or if we can use colors to denote which is the new 99

**Comment by pajlada** [comment]
the previous comment is ofc just a random example, but something along those lines makes more sense to me

**Comment by pajlada** [comment]
The 'rarity' of this is what I think may cause confusion yeah. maybe another thing to try is to see if we can fit this into every level dink in a nice way

**Comment by iProdigy** [comment]
To adapt for every level, we could make it the list of skills that are at the same level or higher

So if you hit 99, it lists all 99+ skills

Or if you hit 50, it lists all 50+ skills

**Comment by iProdigy** [comment]
Latest appearance
image

**Review by pajlada — APPROVED** [review]
I'm happy with the implementation & look of this :+1:

**Pull request merged**
