### PR TITLE
fix: avoid level notif when hopping from leagues

### LINKED ISSUE #612: notif with all stats when hopping from Leagues to Normal worlds
again zzz....

### PR DESCRIPTION
**Pull request by iProdigy**
Closes #612

### CODE REVIEW

**Comment by iProdigy** [comment]
note: if we're not concerned about genuine level ups within 10 seconds of hopping, we can revert https://github.com/pajlads/DinkPlugin/pull/615/commits/b82a2475b175246adce05c8efcd0330877d18211

**Review by Felanbird — APPROVED** [review]
tested bandage commit and it works, don't really care about the 10s window if you're hopping from leagues to get a main game levelup you're probably unhinged

**Comment by iProdigy** [comment]
for clarity: without the bandaid, when hopping btwn two normal worlds, you'd also have to wait 10s post-hop to get level notif. bandaid removes 10s window when hopping btwn two worlds of the same type

**Comment by Felanbird** [comment]
> for clarity: without the bandaid, when hopping btwn two normal worlds, you'd also have to wait 10s post-hop to get level notif. bandaid removes 10s window when hopping btwn two worlds of the same type

ah then we probably should keep it

**Review by pajlada — APPROVED** [review]

**Pull request merged**
